name: Run Preprocessing on Movie Data

on:
  push:
    branches: [main]
    paths:
      - 'automate_movie_recommendation.py'
      - '.github/workflows/preprocess.yml'
      - 'movie_rekomendasi.csv'
  workflow_dispatch:  # memungkinkan manual trigger

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: 🔄 Checkout repository
      uses: actions/checkout@v3

    - name: 🐍 Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 📦 Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: ⚙️ Run preprocessing
      run: |
        python automate_movie_recommendation.py
